### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by t0m5k1** [Jeinzi/thunar-dropbox#1]
So xfce4 is not 4.14 and therefore Thunar is also now 1.8.9 and is fully gtk3
Is this going to be updated to suit as it currently does not appear to be working!

**Comment by Jeinzi** [comment]
I am running Thunar 1.8.9-2 on my Arch machine with Thunar-Dropbox 0.3.1 and it's working as expected.
- Which distro are you running?
- Did you install from the official repos, or did you build the plugin from source?
- Which version of the plugin do you have installed?

**Comment by Jeinzi** [comment]
@t0m5k1 Has your problem resolved itself, or is there something I can do?
In the latter case, please submit some additional info about your setup.
